### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by nicklogin** [bjascob/LemmInflect#12]
Hi, thanks for the amazing tool!

I'm using lemminflect in my project at uni (which may become a paper later). Do you have a paper on it which I could cite?

**Comment by bjascob** [comment]
No, sorry. This is just a GH project.  I didn't write-up a paper on it's construction/operation.  I you need to reference something I'd recommend using the project name, link and release version.  GH keeps all the releases so citing a specific version should point readers to code that's available "forever".

**Comment by nicklogin** [comment]
Thanks! Then I'll cite the repo. I found a guidance for citing GitHub repository at StackExchange, this may be helpful for users who also need to include citation in thieir work

https://academia.stackexchange.com/a/14015
