### ISSUE TITLE
Extension to other languages

### ISSUE THREAD

**Issue by Martijn-Y-ai** [bjascob/LemmInflect#13]
Is it possible to extend the functionality of the inflection to other languages, and if so, what would be required to do so?

**Comment by bjascob** [comment]
No.
The project is based on the [NIH's SPECIALIST Lexicon](https://lsg3.nlm.nih.gov/LexSysGroup/Projects/lexicon/current/web/index.html) which is an English dictionary of words and their inflections.  The overall code here is very English-centric and would require extensive rework even if you could find a similar dictionary for other languages.
