### ISSUE TITLE
Incorrect inflections

### ISSUE THREAD

**Issue by QGB** [bjascob/LemmInflect#17]
['somewhat', ####], ['somew', 'ADJ']

[['his', ####], ['hi', 'PROPN'], ['hi', 'ADJ'], ['hi', 'ADV']],

['her', ####], ['he', 'ADJ'], ['h', 'ADV']],

 [['could', ####], ['coul', 'ADV']

 [['another', ####], ['anoth', 'ADJ'], ['anoth', 'ADV']],

 [['question', ####], ['quest', 'ADV']],

 [['vs', ####], ['v', 'NOUN'], ['v', 'PROPN'], ['v', 'VERB'], ['v', 'ADJ'], ['v', 'ADV']],

**Comment by QGB** [comment]
[['(anything)', ####], ['(anythin', 'VERB'],, ['(anythin', 'ADV']],

**Comment by bjascob** [comment]
Please post the call that you are using that generates the above.

**Comment by bjascob** [comment]
No additional information.
