### ISSUE TITLE
inflection tool for other languages

### ISSUE THREAD

**Issue by evvahu** [bjascob/LemmInflect#20]
Hi,

Thanks for providing this library.
Have you ever thought of implementing other languages? 
If not, I'm currently looking for a tool that does Russian word inflection and I was wondering whether you know of any such tools?

Best,
Eva

**Comment by bjascob** [comment]
LemmInflect is based on a corpus of English (only) word inflections and I don't have this for other languages so it's not possible to implement other languages with this tool. I think NLTK and Spacy only do lemmatization.  I'm not sure if Stanza/CoreNLP has a way to do inflections or if it's just lemmatization but you might want to look at that tool.
