### ISSUE TITLE
Incorrect base form for "install"

### ISSUE THREAD

**Issue by bgoldowsky** [bjascob/LemmInflect#7]
Is it appropriate to report single words that are incorrect as bugs?  I realize the dictionary can't be 100% complete.

Lemminflect 0.2.1:
getAllLemmas('install')
{'VERB': ('install', 'instal')}

I think it should just return 'install'.

**Comment by bjascob** [comment]
Interesting.  Per Google... _Instal is chiefly British variant of install. Merriam Webster defines that. They both mean same (and are pronounced in the same way)_

Even the "wamerican" dictionary I used has both spellings, even though I've never seen this spelled with one "l".

For the cases where there is more than one spelling returned in the tuple, the first should be the most common.  Part of developing the system was to use a corpus to count word occurrences so when multiple spellings exist, they could be ordered based on how commonly they occur.

**Comment by bjascob** [comment]
Closing because this looks like an error but apparently the alternate spelling is acceptable.
